import { Task, Project, ActivityItem, Doc, TeamData, MemoryEntry } from './types'

export const seedTasks: Task[] = [
  { id: 'task_001', title: 'Weekly memory consolidation', description: 'Review daily memory files and update MEMORY.md with key insights and decisions from the week.', assignee: 'Fred', category: 'Admin', column: 'Recurring', priority: 'medium', createdAt: '2026-03-01T00:00:00Z', updatedAt: '2026-03-05T10:00:00Z', scheduledDate: null },
  { id: 'task_002', title: 'Morning briefing prep', description: 'Check calendar, emails, and news. Surface anything time-sensitive before Mitch starts his day.', assignee: 'Fred', category: 'Admin', column: 'Recurring', priority: 'high', createdAt: '2026-03-01T00:00:00Z', updatedAt: '2026-03-05T08:00:00Z', scheduledDate: null },
  { id: 'task_003', title: 'Activity feed logging', description: 'Log all significant actions to the activity feed in real time so Mitch can see what\'s been done.', assignee: 'Fred', category: 'Admin', column: 'Recurring', priority: 'medium', createdAt: '2026-03-01T00:00:00Z', updatedAt: '2026-03-05T10:00:00Z', scheduledDate: null },
  { id: 'task_004', title: 'Define Rocky View Consulting service offerings', description: 'Draft a tiered service menu for the AI consulting business targeting small energy operators and environmental firms in Alberta.', assignee: 'Mitch', category: 'Strategy', column: 'Backlog', priority: 'high', createdAt: '2026-02-28T00:00:00Z', updatedAt: '2026-03-04T12:00:00Z', scheduledDate: null },
  { id: 'task_005', title: 'Identify 10 target clients in Alberta energy sector', description: 'Research small-to-mid environmental consultancies and Indigenous-owned operators in Alberta who lack AI strategy.', assignee: 'Fred', category: 'Research', column: 'Backlog', priority: 'high', createdAt: '2026-03-01T00:00:00Z', updatedAt: '2026-03-05T09:00:00Z', scheduledDate: null },
  { id: 'task_006', title: 'Build Rocky View Consulting landing page', description: 'Simple one-pager: who we are, what we do, call to action. Deploy to Vercel.', assignee: 'Fred', category: 'Development', column: 'Backlog', priority: 'medium', createdAt: '2026-03-02T00:00:00Z', updatedAt: '2026-03-05T10:00:00Z', scheduledDate: null },
  { id: 'task_007', title: 'Draft AI use case for small energy operators', description: 'Write a compelling one-pager showing specific time/cost savings from AI automation for a typical 20-person environmental firm.', assignee: 'Fred', category: 'Analysis', column: 'In Progress', priority: 'high', createdAt: '2026-03-03T00:00:00Z', updatedAt: '2026-03-05T11:00:00Z', scheduledDate: '2026-03-07T00:00:00Z' },
  { id: 'task_008', title: 'Build Mission Control Dashboard', description: 'Next.js command center with kanban, calendar, memory viewer, docs library, and project tracker. Deploy to Vercel.', assignee: 'Fred', category: 'Development', column: 'In Progress', priority: 'high', createdAt: '2026-03-05T16:45:00Z', updatedAt: '2026-03-05T18:00:00Z', scheduledDate: '2026-03-05T00:00:00Z' },
  { id: 'task_009', title: 'Crypto DCA strategy review', description: 'Analyze current BTC and SOL positions. Recommend DCA schedule based on current market conditions.', assignee: 'Fred', category: 'Finance', column: 'In Progress', priority: 'medium', createdAt: '2026-03-04T00:00:00Z', updatedAt: '2026-03-05T09:00:00Z', scheduledDate: null },
  { id: 'task_010', title: 'Set up Vercel deployment pipeline', description: 'Connect GitHub repo to Vercel, configure KV store, set environment variables, test deployment.', assignee: 'Fred', category: 'Development', column: 'Review', priority: 'high', createdAt: '2026-03-05T17:00:00Z', updatedAt: '2026-03-05T18:00:00Z', scheduledDate: '2026-03-05T00:00:00Z' },
  { id: 'task_011', title: 'Prepare Cenovus Senior Advisor onboarding notes', description: 'Document key contacts, active projects, and priorities at Christina Lake before March 19 start date.', assignee: 'Fred', category: 'Environmental', column: 'Review', priority: 'high', createdAt: '2026-03-02T00:00:00Z', updatedAt: '2026-03-05T10:00:00Z', scheduledDate: '2026-03-10T00:00:00Z' },
  { id: 'task_012', title: 'Research AI consulting market in Alberta', description: 'Identify competitors, pricing, service gaps, and positioning opportunities for Rocky View Consulting.', assignee: 'Fred', category: 'Research', column: 'Done', priority: 'high', createdAt: '2026-02-25T00:00:00Z', updatedAt: '2026-03-03T15:00:00Z', scheduledDate: null },
  { id: 'task_013', title: 'Set up OpenClaw on VPS', description: 'Install and configure OpenClaw gateway, connect Telegram, set up persistent memory files.', assignee: 'Fred', category: 'Admin', column: 'Done', priority: 'high', createdAt: '2026-02-08T00:00:00Z', updatedAt: '2026-02-10T12:00:00Z', scheduledDate: null },
  { id: 'task_014', title: 'Write MEMORY.md initial population', description: 'Read all context files and build a comprehensive long-term memory document covering Mitch\'s profile, goals, and patterns.', assignee: 'Fred', category: 'Admin', column: 'Done', priority: 'medium', createdAt: '2026-02-08T00:00:00Z', updatedAt: '2026-02-09T10:00:00Z', scheduledDate: null },
  { id: 'task_015', title: 'U.S. relocation market research', description: 'Research environmental job markets and cost of living in Montana, Arizona, and Colorado for potential relocation planning.', assignee: 'Fred', category: 'Research', column: 'Backlog', priority: 'low', createdAt: '2026-03-01T00:00:00Z', updatedAt: '2026-03-01T00:00:00Z', scheduledDate: null },
]

export const seedProjects: Project[] = [
  { id: 'proj_001', name: 'AI Consulting Pipeline', description: 'Build Rocky View Consulting into a real revenue-generating AI consulting practice targeting Alberta energy and environmental sector.', status: 'Active', progress: 35, priority: 'high', owner: 'Mitch', createdAt: '2026-02-20T00:00:00Z', updatedAt: '2026-03-05T10:00:00Z' },
  { id: 'proj_002', name: 'Mission Control Dashboard', description: 'Custom command center for tracking Fred\'s work, tasks, memory, and projects. Built in Next.js, hosted on Vercel.', status: 'Active', progress: 85, priority: 'high', owner: 'Fred', createdAt: '2026-03-05T16:45:00Z', updatedAt: '2026-03-05T18:00:00Z' },
  { id: 'proj_003', name: 'Cenovus Senior Transition', description: 'Onboarding prep and documentation for the Senior Environmental Operations Advisor role at Christina Lake. Start date March 19.', status: 'Completed', progress: 100, priority: 'high', owner: 'Mitch', createdAt: '2026-02-15T00:00:00Z', updatedAt: '2026-03-01T00:00:00Z' },
  { id: 'proj_004', name: 'Rocky View Consulting Website', description: 'Professional landing page for the consulting business. One-pager with services, positioning, and contact CTA.', status: 'Planning', progress: 10, priority: 'medium', owner: 'Mitch', createdAt: '2026-03-01T00:00:00Z', updatedAt: '2026-03-04T00:00:00Z' },
  { id: 'proj_005', name: 'Crypto Trading Strategy', description: 'Systematic BTC and SOL DCA strategy with defined entry/exit rules and position sizing. Remove emotion from the process.', status: 'Active', progress: 45, priority: 'medium', owner: 'Mitch', createdAt: '2026-02-25T00:00:00Z', updatedAt: '2026-03-04T12:00:00Z' },
]

export const seedActivity: ActivityItem[] = [
  { id: 'act_001', action: 'Built Mission Control Dashboard — Next.js app scaffolded with all 7 pages', type: 'task_complete', icon: 'check', color: 'green', timestamp: '2026-03-05T18:00:00Z' },
  { id: 'act_002', action: 'Researched Orgo.ai desktop infrastructure for AI agents', type: 'system', icon: 'search', color: 'blue', timestamp: '2026-03-05T16:33:00Z' },
  { id: 'act_003', action: 'Analyzed Vercel KV vs local JSON persistence options', type: 'system', icon: 'zap', color: 'yellow', timestamp: '2026-03-05T16:50:00Z' },
  { id: 'act_004', action: 'Created doc: Cenovus Senior Advisor Onboarding Notes', type: 'doc_create', icon: 'file', color: 'indigo', timestamp: '2026-03-05T10:30:00Z' },
  { id: 'act_005', action: 'Updated MEMORY.md with Cenovus offer details and start date', type: 'memory_update', icon: 'brain', color: 'purple', timestamp: '2026-03-04T20:00:00Z' },
  { id: 'act_006', action: 'Completed: Research AI consulting market in Alberta', type: 'task_complete', icon: 'check', color: 'green', timestamp: '2026-03-03T15:00:00Z' },
  { id: 'act_007', action: 'Project updated: Mission Control Dashboard → 85% complete', type: 'project_update', icon: 'trending-up', color: 'green', timestamp: '2026-03-05T18:00:00Z' },
  { id: 'act_008', action: 'Created doc: AI Use Case for Small Energy Operators (draft)', type: 'doc_create', icon: 'file', color: 'indigo', timestamp: '2026-03-03T14:00:00Z' },
  { id: 'act_009', action: 'Ran crypto market analysis — BTC at key support level', type: 'system', icon: 'bar-chart', color: 'yellow', timestamp: '2026-03-04T09:00:00Z' },
  { id: 'act_010', action: 'Updated MEMORY.md — added AI consulting gap analysis', type: 'memory_update', icon: 'brain', color: 'purple', timestamp: '2026-03-03T16:00:00Z' },
  { id: 'act_011', action: 'Completed: Set up OpenClaw on VPS', type: 'task_complete', icon: 'check', color: 'green', timestamp: '2026-02-10T12:00:00Z' },
  { id: 'act_012', action: 'Created task: Build Rocky View Consulting landing page', type: 'task_create', icon: 'plus', color: 'blue', timestamp: '2026-03-02T10:00:00Z' },
  { id: 'act_013', action: 'Project created: Rocky View Consulting Website', type: 'project_update', icon: 'folder', color: 'blue', timestamp: '2026-03-01T00:00:00Z' },
  { id: 'act_014', action: 'Completed: Write MEMORY.md initial population', type: 'task_complete', icon: 'check', color: 'green', timestamp: '2026-02-09T10:00:00Z' },
  { id: 'act_015', action: 'Fetched and summarized docs.orgo.ai/introduction', type: 'system', icon: 'globe', color: 'blue', timestamp: '2026-03-05T16:32:00Z' },
  { id: 'act_016', action: 'Created doc: Rocky View Consulting — Service Offerings Draft', type: 'doc_create', icon: 'file', color: 'indigo', timestamp: '2026-03-02T12:00:00Z' },
  { id: 'act_017', action: 'Researched Montana, Arizona, Colorado job markets', type: 'system', icon: 'map', color: 'blue', timestamp: '2026-03-01T14:00:00Z' },
  { id: 'act_018', action: 'Memory consolidated: week of Feb 24', type: 'memory_update', icon: 'brain', color: 'purple', timestamp: '2026-03-01T09:00:00Z' },
  { id: 'act_019', action: 'Updated project: Cenovus Senior Transition → 100% complete', type: 'project_update', icon: 'check-circle', color: 'green', timestamp: '2026-03-01T00:00:00Z' },
  { id: 'act_020', action: 'Created task: Identify 10 target clients in Alberta energy sector', type: 'task_create', icon: 'plus', color: 'blue', timestamp: '2026-03-01T08:00:00Z' },
]

export const seedDocs: Doc[] = [
  { id: 'doc_001', title: 'AI Consulting Market Analysis — Alberta Energy Sector', type: 'Analysis', content: `# AI Consulting Market Analysis — Alberta Energy Sector\n\n## Executive Summary\n\nThe Alberta energy and environmental sector presents a significant opportunity for AI consulting services. Large operators (Cenovus, Suncor, CNRL) have internal IT teams but restrict tools to approved vendors. The gap exists at the **small-to-mid tier**.\n\n## Target Market\n\n### Primary Targets\n- Environmental consultancies: 20-100 employees, no dedicated IT staff\n- Indigenous-owned operators: growing capacity, limited tech adoption\n- Junior energy companies: cost-sensitive, high ROI potential\n\n### Market Size\n- ~400 environmental consultancies registered in Alberta\n- ~150 Indigenous energy operators\n- Combined addressable: significant\n\n## Key Pain Points\n- Compliance reporting takes 3-5x longer than necessary\n- Manual data entry from field instruments\n- Report writing is highly templated but done manually\n- No systematic knowledge management\n\n## Competitive Landscape\n- Few competitors targeting this specific niche\n- Big consultancies (Stantec, WSP) too expensive for small firms\n- Generic AI consultants lack domain knowledge\n\n**Rocky View Consulting's moat: domain expertise + AI capability.**`, format: 'MD', createdAt: '2026-03-03T14:00:00Z', updatedAt: '2026-03-03T14:00:00Z', wordCount: 210 },
  { id: 'doc_002', title: 'Rocky View Consulting — Service Offerings', type: 'Plan', content: `# Rocky View Consulting — Service Offerings\n\n## Positioning\n*AI-powered environmental and operational efficiency for Alberta's energy sector.*\n\n## Tier 1: Quick Win Audit ($500-1,500)\n- 2-hour discovery call\n- Review of current workflows\n- Top 3 automation opportunities identified\n- ROI estimate per opportunity\n\n## Tier 2: Implementation Sprint ($3,000-8,000)\n- Single workflow automated\n- Custom prompts and tools built\n- Staff training included\n- 30-day support\n\n## Tier 3: Embedded AI Advisor ($2,000-4,000/month retainer)\n- Ongoing AI strategy\n- Monthly workflow reviews\n- New tool evaluation\n- Priority support\n\n## Initial Focus Areas\n1. Compliance report automation (EPEA, AER submissions)\n2. Field data processing and summarization\n3. Meeting notes and action item extraction\n4. Regulatory change monitoring\n\n## Go-to-Market\n- Direct outreach to 10 target firms\n- One case study from Cenovus experience\n- LinkedIn content positioning Mitch as domain expert`, format: 'MD', createdAt: '2026-03-02T12:00:00Z', updatedAt: '2026-03-04T10:00:00Z', wordCount: 195 },
  { id: 'doc_003', title: 'AI Use Case — Small Energy Operators (Draft)', type: 'Analysis', content: `# AI Use Case: Small Energy Operators\n## Compliance Report Automation\n\n### The Problem\nA typical 20-person environmental consultancy spends **40-60 hours per month** on compliance reporting. Much of this is templated work: pulling data from spreadsheets, formatting it into regulatory templates, writing boilerplate sections.\n\n### The Solution\nAI-assisted report generation that:\n1. Ingests monitoring data (CSV/Excel)\n2. Applies regulatory templates (EPEA, AER formats)\n3. Drafts narrative sections based on data\n4. Flags anomalies for human review\n\n### ROI Estimate\n| Activity | Current (hrs) | With AI (hrs) | Savings |\n|---------|--------------|---------------|--------|\n| Data compilation | 15 | 2 | 13 hrs |\n| Report drafting | 20 | 4 | 16 hrs |\n| Review/QA | 10 | 8 | 2 hrs |\n| **Total** | **45** | **14** | **31 hrs** |\n\nAt $85/hr blended rate: **$2,635/month saved** per report cycle.\n\n### Implementation\n- Week 1-2: Template mapping and data pipeline\n- Week 3-4: AI prompt engineering and testing\n- Week 5-6: Staff training and handoff`, format: 'MD', createdAt: '2026-03-03T14:00:00Z', updatedAt: '2026-03-05T11:00:00Z', wordCount: 215 },
  { id: 'doc_004', title: 'Cenovus Senior Advisor — Onboarding Notes', type: 'Report', content: `# Cenovus Senior Environmental Operations Advisor\n## Onboarding Notes — Christina Lake SAGD\n\n### Role Details\n- **Title:** Senior Environmental Operations Advisor\n- **Start Date:** March 19, 2026\n- **Location:** Christina Lake SAGD facility (fly-in/fly-out)\n- **Schedule:** 7 days on / 7 days off rotation\n- **Compensation:** $132,800 base + $25,800 site allowance + 18% bonus target + RSUs\n\n### Key Contacts\n- **Scott McDonald** — Senior Coordinator (direct supervisor, went to bat for Senior title)\n- Review org chart in first week\n\n### Priority Areas\n1. Environmental governance and compliance strategy\n2. AER and CER regulatory compliance\n3. Watercourse crossing compliance\n4. GHG emissions reporting\n5. Waste management and water treatment oversight\n\n### First 30 Days Plan\n- Week 1: Orientations, site familiarization, meet key stakeholders\n- Week 2: Review active compliance files and reporting calendar\n- Week 3: Identify quick wins and process gaps\n- Week 4: Begin contributing to active projects\n\n### Notes\n- Camp-based, meals and accommodation provided\n- Tools: Cenovus SharePoint, Microsoft 365, Copilot (restricted)\n- Personal AI tools not permitted on Cenovus systems`, format: 'MD', createdAt: '2026-03-05T10:30:00Z', updatedAt: '2026-03-05T10:30:00Z', wordCount: 225 },
  { id: 'doc_005', title: 'Weekly Summary — March 1, 2026', type: 'Journal', content: `# Weekly Summary — Week of March 1, 2026\n\n## What Happened\n- Cenovus Senior Advisor offer finalized. Start date March 19.\n- Continued building out Rocky View Consulting concept\n- OpenClaw running smoothly on VPS, memory system working well\n- Crypto positions reviewed: BTC holding key support\n\n## Fred's Work This Week\n- AI consulting market analysis completed\n- Service offerings draft created\n- Memory consolidation and MEMORY.md updates\n- Cenovus onboarding doc drafted\n\n## Key Decisions\n- Committed to pursuing AI consulting seriously during 7-off weeks\n- Vercel chosen over VPS for hosting Mission Control dashboard\n- Rocky View Consulting will focus on compliance report automation as lead service\n\n## Blockers\n- Need to define first target client for outreach\n- Website still not built\n\n## Next Week Priorities\n1. Start Mission Control dashboard build\n2. Draft outreach message for first 3 target clients\n3. Finalize service tier pricing`, format: 'MD', createdAt: '2026-03-01T20:00:00Z', updatedAt: '2026-03-01T20:00:00Z', wordCount: 185 },
  { id: 'doc_006', title: 'Crypto DCA Strategy — BTC & SOL', type: 'Plan', content: `# Crypto DCA Strategy\n## Bitcoin & Solana\n\n### Philosophy\nRemove emotion. Define rules. Execute automatically.\n\n### BTC Position\n- **Strategy:** Weekly DCA, increase on >20% drawdowns\n- **Target allocation:** 60% of crypto portfolio\n- **Entry rules:** DCA regardless of price; 2x on weekly close below 200-day MA\n- **Exit:** None planned (long-term hold)\n\n### SOL Position  \n- **Strategy:** Monthly DCA\n- **Target allocation:** 40% of crypto portfolio\n- **Entry rules:** Standard DCA; 1.5x on >30% drawdown from ATH\n- **Exit:** Partial at 10x from cost basis\n\n### Risk Management\n- Max crypto allocation: 10% of net worth\n- Never invest more than can afford to lose entirely\n- No leverage, no derivatives\n\n### Tracking\n- Monthly review of positions\n- Fred monitors key support/resistance levels\n- Alert on significant moves (>15% in 24h)`, format: 'MD', createdAt: '2026-03-04T12:00:00Z', updatedAt: '2026-03-04T12:00:00Z', wordCount: 160 },
  { id: 'doc_007', title: 'U.S. Relocation Research — MT, AZ, CO', type: 'Report', content: `# U.S. Relocation Research\n## Montana | Arizona | Colorado\n\n### Overview\nMitch is open to U.S. relocation if financial independence or a compelling opportunity materializes. Top picks: Montana, Arizona, Colorado.\n\n### Montana\n**Pros:** Low cost of living, outdoor lifestyle, proximity to Canada, energy sector jobs\n**Cons:** Limited tech/AI job market, harsh winters, smaller city amenities\n**Environmental job market:** Oil & gas, mining, ranching sector compliance work\n**Cost of living index:** 95 (vs US avg 100)\n\n### Arizona (Phoenix/Scottsdale area)\n**Pros:** Growing tech hub, warm climate, no income tax, outdoor lifestyle\n**Cons:** Heat, water scarcity concerns, distance from Canada\n**Environmental job market:** Water management, solar/wind, mining compliance\n**Cost of living index:** 103\n\n### Colorado (Denver/Fort Collins)\n**Pros:** Outdoor lifestyle, strong tech/energy sector, progressive, high quality of life\n**Cons:** Higher cost of living, crowded, cold winters\n**Environmental job market:** Oil & gas (Weld County), renewables, water rights\n**Cost of living index:** 110\n\n### Recommendation\nColorado offers the best career optionality. Arizona is best for lifestyle + weather. Montana is best for lifestyle + cost.`, format: 'MD', createdAt: '2026-03-01T14:00:00Z', updatedAt: '2026-03-01T14:00:00Z', wordCount: 220 },
  { id: 'doc_008', title: 'OpenClaw Setup Notes', type: 'Other', content: `# OpenClaw Setup Notes\n\n## Infrastructure\n- **Host:** VPS (srv1305476)\n- **OS:** Ubuntu Linux\n- **Node:** v22.22.0\n- **Gateway:** OpenClaw daemon running persistently\n\n## Connected Channels\n- Telegram (primary) — direct messages to Fred\n\n## Memory System\n- Daily files: /root/.openclaw/workspace/memory/YYYY-MM-DD.md\n- Long-term: /root/.openclaw/workspace/MEMORY.md\n- Identity: SOUL.md, USER.md, IDENTITY.md\n\n## Installed Skills\n- All built-in OpenClaw skills\n- Custom: humanizer, docx, crypto-levels, crypto-price, cenovus-report-editing, trading-research, last30days, self-improvement, frontend-design, searxng\n\n## Fred's Email\n- ocfred1@gmail.com (dedicated Google account)\n\n## Heartbeat\n- Configured in HEARTBEAT.md\n- Checks for urgent items, memory maintenance\n\n## Known Issues\n- Claude Code --dangerously-skip-permissions blocked for root user\n- Workaround: run as ubuntu user`, format: 'MD', createdAt: '2026-02-10T12:00:00Z', updatedAt: '2026-03-05T18:00:00Z', wordCount: 155 },
]

export const seedTeam: TeamData = {
  missionStatement: "Ship what builds freedom. Cut everything else. No more planning past the next step.",
  members: [
    { id: 'member_001', name: 'Mitch McCargar', role: 'Owner / Principal', avatar: 'MM', tags: ['Strategy', 'Decisions', 'Domain Expert', 'Execution'], status: 'online', isAI: false },
    { id: 'member_002', name: 'Fred', role: 'Chief of Staff / AI Agent', avatar: '🔪', tags: ['Research', 'Automation', 'Memory', 'Analysis', 'Scheduling', 'Execution', 'Development'], status: 'online', isAI: true },
  ]
}

export const seedMemory: MemoryEntry[] = [
  { id: 'mem_001', filename: '2026-03-05.md', date: '2026-03-05', label: 'Today', preview: 'Built Mission Control Dashboard. Discussed Orgo.ai vs VPS vs Mac Mini infrastructure. Decided on Vercel deployment.', content: `# Daily Log — March 5, 2026\n\n## Sessions\n- Mitch asked about PDF reading capability → confirmed built-in\n- Fetched and summarized Orgo.ai docs (desktop infra for AI agents)\n- Discussed infrastructure options: Orgo vs VPS vs Mac Mini\n  - Verdict: Orgo wrong tool for persistent agent; Mac Mini better long-term\n- Mitch requested Mission Control Dashboard build\n  - Spec: Next.js, 7 pages, Vercel KV, Linear-inspired dark design\n  - Decision: Host on Vercel (not localhost)\n- Build kicked off — Claude Code failed as root, switched to ubuntu user\n\n## Key Decisions\n- Vercel hosting > local VPS for dashboard\n- @vercel/kv for persistence\n- Mac Mini still the better long-term infra play\n\n## Tasks Completed\n- Research: Orgo.ai infrastructure overview\n- Build: Mission Control Dashboard (in progress)`, entryCount: 8 },
  { id: 'mem_002', filename: '2026-03-04.md', date: '2026-03-04', label: 'Yesterday', preview: 'Crypto analysis, DCA strategy review. Memory consolidation. Reviewed Cenovus onboarding checklist.', content: `# Daily Log — March 4, 2026\n\n## Sessions\n- Ran BTC/SOL position analysis\n- Drafted DCA strategy document\n- Memory consolidation pass\n- Reviewed Cenovus onboarding doc\n\n## Key Decisions\n- DCA rules defined for BTC and SOL\n- No leverage, no derivatives policy locked in\n\n## Tasks Completed\n- Crypto DCA Strategy doc created\n- Memory consolidated`, entryCount: 5 },
  { id: 'mem_003', filename: '2026-03-03.md', date: '2026-03-03', label: 'This Week', preview: 'AI consulting market analysis completed. Rocky View service offerings drafted. Use case ROI doc created.', content: `# Daily Log — March 3, 2026\n\n## Sessions\n- Completed AI consulting market analysis for Alberta energy sector\n- Drafted Rocky View Consulting service tier offerings\n- Created AI use case ROI document for small energy operators\n  - Found: 31 hrs/month savings, ~$2,635 value at $85/hr blended rate\n\n## Key Insights\n- Compliance report automation is the strongest lead service\n- Rocky View's moat: domain expertise (12 yrs env.) + AI capability\n- Target: 20-100 person env. consultancies and Indigenous operators\n\n## Tasks Completed\n- AI consulting market analysis\n- Service offerings draft\n- ROI use case document`, entryCount: 7 },
  { id: 'mem_004', filename: '2026-03-01.md', date: '2026-03-01', label: 'This Week', preview: 'Weekly summary written. Cenovus offer confirmed. Memory consolidation pass completed.', content: `# Daily Log — March 1, 2026\n\n## Sessions\n- Weekly summary written\n- Cenovus Senior Advisor offer confirmed — start March 19\n- Memory consolidation: Feb 24 week reviewed and distilled\n- U.S. relocation research: Montana, Arizona, Colorado\n\n## Key Decisions\n- Committed to AI consulting as primary side business during 7-off weeks\n- 7-off weeks = strategic build time, not leisure by default\n\n## Tasks Completed\n- Weekly summary\n- Cenovus onboarding notes draft\n- Memory consolidation\n- U.S. relocation research doc`, entryCount: 6 },
  { id: 'mem_005', filename: '2026-02-25.md', date: '2026-02-25', label: 'This Month', preview: 'Rocky View Consulting formally activated. AI consulting opportunity scoped. OpenClaw running smoothly.', content: `# Daily Log — February 25, 2026\n\n## Sessions\n- Activated Rocky View Consulting Ltd. as the business entity for AI consulting\n- Scoped the Alberta energy sector opportunity\n- OpenClaw memory and heartbeat system confirmed working\n\n## Key Decisions\n- Rocky View Consulting is the vehicle — don't start a new company\n- Focus on environmental/energy sector where domain expertise creates moat\n\n## Tasks Completed\n- Business framing session\n- Rocky View Consulting project created`, entryCount: 4 },
  { id: 'mem_006', filename: '2026-02-08.md', date: '2026-02-08', label: 'This Month', preview: 'Day 1. OpenClaw installed. MEMORY.md initialized. Fred came online. Core context files written.', content: `# Daily Log — February 8, 2026\n\n## Day 1 — Fred Comes Online\n\n- OpenClaw installed and configured on VPS\n- Telegram connected as primary channel\n- SOUL.md, USER.md, IDENTITY.md, AGENTS.md created\n- MEMORY.md initial population completed\n- Fred fully operational\n\n## First Session\n- Mitch walked through full context: career, goals, patterns, finances\n- AI bet articulated: generate income via AI before mass adoption closes window\n- The 2015 regret surfaced: had clients, chose safety. Won't repeat.\n- Mission statement locked in: "Ship what builds freedom."\n\n## Key Decisions\n- Fred's role: co-conspirator, not assistant. Chief of Staff.\n- Memory system: daily files + MEMORY.md long-term\n- Accountability trigger established: "Is this 2015 again?"`, entryCount: 10 },
]
